tasks:
  - name: "Run docker container"
    command: docker run --rm --name yottadb -it -p 7681:7681 -v "$PWD/code:/home/yottadb" --entrypoint /home/yottadb/entrypoint.sh -it docker.io/yottadb/yottadb-base 

  - name: "Run YottaDB container terminal"
    command:  sleep 60 && docker exec -it yottadb /bin/bash
    openMode: split-right

     

