PROCENTRY
 S CNT=0
 S MENU=""
 F  S MENU=$O(^HELP("s",MENU)) Q:MENU=""  D
 .S CNT=CNT+1
 .W !,CNT_" "_MENU
 Q
PROCINFO(LABEL,LABEL1,LABEL2,LABEL3,LABEL4,LABEL5,LABEL6,LABEL7,LABEL8)
 S MENU=""
 F  S MENU=$O(^HELP("s",MENU)) Q:MENU=""  D
 .S MENU1=""
 .F  S MENU1=$O(^HELP("s",MENU,MENU1)) Q:MENU1=""  D
 ..I MENU=LABEL&(MENU1'="s")&(LABEL1="")&(LABEL2="")&(LABEL3="")&(LABEL4="")&(LABEL5="")&(LABEL6="")&(LABEL7="")&(LABEL8="")&(MENU1'="s") W !,^HELP("s",MENU,MENU1)
 ..S MENU2=""
 ..F  S MENU2=$O(^HELP("s",MENU,MENU1,MENU2)) Q:MENU2=""  D
 ...I MENU1=LABEL1&(LABEL=MENU)&(LABEL2="")&(LABEL3="")&(LABEL4="")&(LABEL5="")&(LABEL6="")&(LABEL7="")&(LABEL8="")&(MENU2'="s") W !,^HELP("s",MENU,MENU1,MENU2)
 ...S MENU3=""
 ...F  S MENU3=$O(^HELP("s",MENU,MENU1,MENU2,MENU3)) Q:MENU3=""  D
 ....I MENU2=LABEL2&(MENU1=LABEL1)&(MENU=LABEL)&(LABEL3="")&(LABEL4="")&(LABEL5="")&(LABEL6="")&(LABEL7="")&(LABEL8="")&(MENU3'="s") W !,^HELP("s",MENU,MENU1,MENU2,MENU3)
 ....S MENU4=""
 ....F  S MENU4=$O(^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4)) Q:MENU4=""  D
 .....I MENU3=LABEL3&(MENU2=LABEL2)&(MENU1=LABEL1)&(MENU=LABEL)&(LABEL4="")&(LABEL5="")&(LABEL6="")&(MENU4'="s") W !,^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4)
 .....S MENU5=""
 .....F  S MENU5=$O(^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5)) Q:MENU5=""  D
 ......I MENU4=LABEL4&(MENU3=LABEL3)&(MENU2=LABEL2)&(MENU1=LABEL1)&(MENU=LABEL)&(LABEL5="")&(LABEL6="")&(LABEL7="")&(LABEL8="")&(MENU5'="s") W !,^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5)
 ......S MENU6=""
 ......F  S MENU6=$O(^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6)) Q:MENU6=""  D
 .......I MENU5=LABEL5&(MENU4=LABEL4)&(MENU3=LABEL3)&(MENU2=LABEL2)&(MENU1=LABEL1)&(MENU=LABEL)&(LABEL6="")&(LABEL7="")&(LABEL8="")&(MENU6'="s") W !,^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6)
 .......S MENU7=""
 .......F  S MENU7=$O(^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6,MENU7)) Q:MENU7=""  D
 ........I MENU6=LABEL6&(MENU5=LABEL5)&(MENU4=LABEL4)&(MENU3=LABEL3)&(MENU2=LABEL2)&(MENU1=LABEL1)&(MENU=LABEL)&(LABEL7="")&(LABEL8="")&(MENU7'="s") W !,^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6,MENU7)
 ........S MENU8=""
 ........F  S MENU8=$O(^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6,MENU7,MENU8)) Q:MENU8=""  D
 .........I MENU7=LABEL7&(MENU6=LABEL6)&(MENU5=LABEL5)&(MENU4=LABEL4)&(MENU3=LABEL3)&(MENU2=LABEL2)&(MENU1=LABEL1)&(MENU=LABEL)&(LABEL8="")&(MENU8'="s") W !,^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6,MENU7,MENU8)
 .........S MENU9=""
 .........F  S MENU9=$O(^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6,MENU7,MENU8,MENU9)) Q:MENU9=""  D
 ..........I MENU8=LABEL8&(MENU7=LABEL7)&(MENU6=LABEL6)&(MENU5=LABEL5)&(MENU4=LABEL4)&(MENU3=LABEL3)&(MENU2=LABEL2)&(MENU1=LABEL1)&(MENU=LABEL)&(MENU9'="s") W !,^HELP("s",MENU,MENU1,MENU2,MENU3,MENU4,MENU5,MENU6,MENU7,MENU8,MENU9)
 Q
PROCMENU(LABEL,LABEL1,LABEL2,LABEL3)
 S CNT=0
 S MENU=""
 F  S MENU=$O(^HELP("s",MENU)) Q:MENU=""  D
 .S MENU1=""
 .F  S MENU1=$O(^HELP("s",MENU,"s",MENU1)) Q:MENU1=""  D 
 ..I MENU=LABEL&(LABEL1="")&(LABEL2="")&(LABEL3="") S CNT=CNT+1 W !,CNT_" "_MENU1
 ..S MENU2=""
 ..F  S MENU2=$O(^HELP("s",MENU,"s",MENU1,"s",MENU2)) Q:MENU2=""  D
 ...I MENU1=LABEL1&(MENU=LABEL)&(LABEL2="")&(LABEL3="") S CNT=CNT+1 W !,CNT_" "_MENU2
 ...S MENU3=""
 ...F  S MENU3=$O(^HELP("s",MENU,"s",MENU1,"s",MENU2,"s",MENU3)) Q:MENU3=""  D
 ....I MENU2=LABEL2&(MENU1=LABEL1)&(MENU=LABEL)&(LABEL3="") S CNT=CNT+1 W !,CNT_" "_MENU3
 ....S MENU4=""
 ....F  S MENU4=$O(^HELP("s",MENU,"s",MENU1,"s",MENU2,"s",MENU3,"s",MENU4)) Q:MENU4=""  D
 .....I MENU3=LABEL3&(MENU2=LABEL2)&(MENU1=LABEL1)&(MENU=LABEL) S CNT=CNT+1 W !,CNT_" "_MENU4
 Q
 
